---
title: "Econometrics"
author: "Austin Kennedy"
date: "1/29/2022"
output: html_document
---

```{r Clear memory and setup}
rm(list=ls())
options(scipen=999)
```


```{r Packages}
library(tidyverse)
library(fixest)
library(data.table)
library(broom)
library(modelsummary)
library(msm)
```

```{r Load Data}
volumes <- read.csv("../input/volumes_all_opt_percentile.csv")
```

```{r Clean up}
volumes <- volumes[,-1] #Drops 'X' which is just the index attached by Python
```

```{r Create years and bins}
years <- seq(1510,1890, by=1)
bins <- seq(1610, 1890, by = 20)
```



```{r Assign volumes to bins}

#Merge volume years to closest bin
a = data.table(Value=volumes$Year_rounded) #Extract years

a[,merge:=Value] #Give data.table something to merge on

b = data.table(Value = bins)

b[,merge:=Value]

setkeyv(a, c('merge')) #Sort for quicker merge

setkeyv(b, c('merge'))

rounded = b[a, roll='nearest'] #Merge to nearest

rounded <- distinct(rounded) #Get distinct values for easier merge to 'volumes'

# volumes <- data.table(volumes)

volumes <- merge(volumes, rounded, by.x = "Year_rounded", by.y = "merge")

#Remove unnecessary column
volumes <- volumes %>%
  subset(select = -c(i.Value)) %>%
  rename(bin_20 = Value)

```

```{r Regressions}
volumes <- as.tibble(volumes)
#Regression by year

# mod1 <- volumes %>% group_by(bin_20) %>%
#   do(tidy(feols(Percentile ~ Science + Politics + Science*Religion + Science*Politics + Religion*Politics, data = .)))

mod1 <- volumes %>% group_by(bin_20) %>%
  do(x = lm(Percentile ~ Science + Politics + Science*Religion + Science*Politics + Religion*Politics - Religion, data = .))
```

```{r Marginal Effects and Predicted Values}
#Make empty dataframes
s100 <- as_tibble(matrix(0, length(bins), 8))
colnames(s100) <- c("label", "bin", "marginal", "se", "y_hat", "lower", "upper", "se_fit")
s100 <- s100 %>%
  mutate(bin = bins, label = "s100")

s50p50 <- as_tibble(matrix(0, length(bins), 8))
colnames(s50p50) <-  c("label", "bin", "marginal", "se", "y_hat", "lower", "upper", "se_fit")
s50p50 <- s50p50 %>%
  mutate(bin = bins, label = "s50p50")

s50r50 <- as_tibble(matrix(0, length(bins), 8))
colnames(s50r50) <-  c("label", "bin", "marginal", "se", "y_hat", "lower", "upper", "se_fit")
s50r50 <- s50r50 %>%
  mutate(bin = bins, label = "s50r50")

thirds <- as_tibble(matrix(0, length(bins), 8))
colnames(thirds) <-  c("label", "bin", "marginal", "se", "y_hat", "lower", "upper", "se_fit")
thirds <- thirds %>%
  mutate(bin = bins, label = "thirds")

pred <- function(lm, sci, pol, rel){
  data <- data.frame(Science = sci, Politics = pol, Religion = rel)
  prediction <- predict(lm, newdata = data, interval = "confidence", se.fit =TRUE)
  value <- c(prediction$fit[1], prediction$fit[2], prediction$fit[3], prediction$se.fit)
  return(value)
}

for (i in 1:length(bins)){
  betas <- coef(mod1$x[[i]])
  covar <- vcov(mod1$x[[i]])
  
  s100[i,3] <- betas["Science"]
  s100[i,4] <- deltamethod(~ x2, betas, covar)
  s100[i,5:8] <- as.list(pred(mod1$x[[i]], 1, 0, 0))

  
  s50r50[i,3] <- betas["Science"]*0.5 + betas["Science:Religion"]*0.5
  s50r50[i,4] <- deltamethod(~ x2*0.5 + x4*0.5, betas, covar)
  s50r50[i,5:8] <- as.list(pred(mod1$x[[i]], 0.5, 0 ,0.5))
  
  s50p50[i,3] <- betas["Science"]*0.5 + betas["Science:Politics"]*0.5
  s50p50[i,4] <- deltamethod(~ x2*0.5 + x5*0.5, betas, covar)
  s50p50[i,5:8] <- as.list(pred(mod1$x[[i]], 0.5, 0.5, 0))
  
  thirds[i,3] <- betas["Science"]*(1/3) + betas["Science:Religion"]*(1/3) + betas["Science:Politics"]*(1/3)
  thirds[i,4] <- deltamethod(~ x2*(1/3) + x4*(1/3) + x5*(1/3), betas, covar)
  thirds[i,5:8] <- as.list(pred(mod1$x[[i]], (1/3), (1/3), (1/3)))
}

#combine into one dataset for easier plotting
marg_pred <- rbind(s100, s50r50, s50p50, thirds)

```

```{r Marginal Effects Plot}
marginal_fig <- ggplot(marg_pred, aes(x = bin, y = marginal, group = label)) +
  geom_line(aes(color = label)) +
  geom_ribbon(aes(y = marginal, ymin = marginal - 1.96*se, ymax = marginal + 1.96*se, fill = label), alpha = 0.2) +
  labs(title = "Marginal Effects", x = "Year", y = "Value") +
  scale_color_discrete(breaks = c("s100", "s50p50", "s50r50", "thirds"),
                      labels = c("100% Science", "50% Science 50% Politics", "50% Science 50% Religion", "1/3 Each")) +
  scale_fill_discrete(breaks = c("s100", "s50p50", "s50r50", "thirds"),
                      labels = c("100% Science", "50% Science 50% Politics", "50% Science 50% Religion", "1/3 Each"))

show(marginal_fig)

```

```{r Predicted Values Plot}
marginal_fig <- ggplot(marg_pred, aes(x = bin, y = y_hat, group = label)) +
  geom_line(aes(color = label)) +
  geom_ribbon(aes(y = y_hat, ymin = y_hat - se_fit, ymax = y_hat + se_fit, fill = label), alpha = 0.2) +
  labs(title = "Predicted Value", x = "Year", y = "Value") +
  scale_color_discrete(breaks = c("s100", "s50p50", "s50r50", "thirds"),
                      labels = c("100% Science", "50% Science 50% Politics", "50% Science 50% Religion", "1/3 Each")) +
  scale_fill_discrete(breaks = c("s100", "s50p50", "s50r50", "thirds"),
                      labels = c("100% Science", "50% Science 50% Politics", "50% Science 50% Religion", "1/3 Each"))

marginal_fig_ci <- ggplot(marg_pred, aes(x = bin, y = y_hat, group = label)) +
  geom_line(aes(color = label)) +
  geom_ribbon(aes(y = y_hat, ymin = lower, ymax = upper, fill = label), alpha = 0.2) +
  labs(title = "Predicted Value", x = "Year", y = "Value") +
  scale_color_discrete(breaks = c("s100", "s50p50", "s50r50", "thirds"),
                      labels = c("100% Science", "50% Science 50% Politics", "50% Science 50% Religion", "1/3 Each")) +
  scale_fill_discrete(breaks = c("s100", "s50p50", "s50r50", "thirds"),
                      labels = c("100% Science", "50% Science 50% Politics", "50% Science 50% Religion", "1/3 Each"))

show(marginal_fig)
show(marginal_fig_ci)
```

```{r Create Year and Bin Dummies}
#Create empty data frame with row dimension same as 'volumes', column dimension 'years'
#Column names are 
# year_dummies <- data.frame(matrix(0, nrow = nrow(volumes), ncol = length(years),
#                   dimnames = list(NULL, paste0("x", seq(years[1],years[length(years)],by =1)))))
# 
# #Populate with dummies
# for (i in 1:length(years)){
#   year <- years[i]
#   year_dummies[i] <- ifelse(volumes$Year_rounded >= (year - 10) & volumes$Year_rounded <= (year + 10), 1, 0)
# }
# 
# bin_dummies <- data.frame(matrix(0, nrow = nrow(volumes), ncol = length(bins),
#                   dimnames = list(NULL, paste0("x", seq(bins[1],bins[length(bins)], by=20)))))
# 
# for (i in 1:length(bins)){
#   year <- bins[i]
#   bin_dummies[i] <- ifelse(volumes$Year_rounded >= (year - 10) & volumes$Year_rounded <= (year + 10), 1, 0)
# }
# 
# rounded <- which.min(abs(volumes$Year_rounded - bins))
```

```{r Create interactions}
# sci_year <- volumes$Science*year_dummies
# pol_year <- volumes$Politics*year_dummies
# 
# #Rename column names, regression cannot have repeated col names
# names(sci_year) <- gsub("x", "s", names(sci_year), fixed=TRUE) 
# names(pol_year) <- gsub("x", "p", names(pol_year), fixed=TRUE)
# sci_year %>% rename_with( ~ paste0())
```

```{r Merge data}
# df <- cbind(volumes, year_dummies, sci_year, pol_year)
df <- cbind(volumes, year_dummies)
df2 <- cbind(volumes, bin_dummies)
```

```{r Regressions using bins}
#Choose which year to omit
# a <- 1800
# 
# reg_omit <- c("Year_rounded", "Optimism", "Religion", paste0("x", a), paste0("s", a), paste0("p", a))

dummies <- paste0("x", 1510:1890)

# model <- lm(Percentile ~. - Year_rounded - Optimism - Religion - x1800 - s1800 - p1800, data = df)
# model <- lm(Percentile ~. - Year_rounded - Optimism - Religion - b, data = df)
model_1 <- feols(Percentile ~ Science + Politics, df)
model_2 <- feols(Percentile ~ Science + Politics + .[dummies], df)
model_3 <- feols(Percentile ~ Science + Politics + .[dummies] + .[".[dummies]*Science"] + .[".[dummies]*Politics"], df)
  
model_4 <- feols(Percentile ~ Science + Politics + Science*Politics + Science*Religion + Religion*Politics - Religion, df)
# model_1 <- lm(Percentile ~ Science + Politics, data = df)
# model_2 <- lm(Percentile ~., data = df[, !(colnames(df) %in% reg_omit)])
model_5 <- feols(Percentile ~ Science + Politics + Science*Politics + Science*Religion + Religion*Politics + .[dummies] - Religion , data = df)

model_6 <- feols(Percentile ~ Science + Politics + Science*Politics + Science*Religion + Religion*Politics + .[dummies] + .[".[dummies]*Science"] + .[".[dummies]*Politics"] + .[".[dummies]*Science*Politics"] + .[".[dummies]*Science*Religion"] + .[".[dummies]*Religion*Politics"] - Religion, data = df)


```

```{r Tables for main coefficients}
library(stargazer)
library(modelsummary)
library(broom)
# etable(list(model_1, model_2, model_3),
#        drop = "x1"
#        )
# 
# stargazer(model_1, model_2, model_3, type = 'text')
# etable(model_1)
# etable(model_2)
# etable(model_3)
# summary(model_4)
# modelsummary(list(model_1, model_2, model_3),
#              coef_omit = "[^Science|Politics|(Intercept)|Science × Politics]",
#              output="markdown")

models <- list(model_1, model_2, model_3, model_4, model_5, model_6)
time_fe <- data.frame(
  "Coefficients" = "Time FE",
  "Model 1" = "No",
  "Model 2" = "Yes",
  "Model 3" = "Yes",
  "Model 4" = "No",
  "Model 5" = "Yes",
  "Model 6" = "Yes"
)
time_fe_int <- data.frame(
  "Coefficients" = "Time FE Interactions",
  "Model 1" = "No",
  "Model 2" = "No",
  "Model 3" = "Yes",
  "Model 4" = "No",
  "Model 5" = "No",
  "Model 6" = "Yes"
)

rows <- rbind.data.frame(time_fe,time_fe_int)


attr(rows, "position") <- c(13,14)
modelsummary(models,
             coef_omit = "x1",
             add_rows = rows,
             stars = TRUE,
             gof_omit = "R2 Within|R2 P|Log|AIC|BIC|Std",
             output="latex")

modelsummary(models, 
             statistic = NULL,
             stars = TRUE,
             output = "../output/results.txt")
```

```{r Get coefficients}
library(broom)
results <- tidy(model)

a1 <- results %>% filter(term == "(Intercept)") %>% pull(estimate)
a2 <- results %>% filter(term == "Politics") %>% pull(estimate)
a3 <- results %>% filter(term == "Science") %>% pull(estimate)
a4 <- results %>% filter(substr(term, 1, 1) == "p") %>% pull(estimate)
a5 <- results %>% filter(substr(term, 1, 1) == "s") %>% pull(estimate)
a6 <- results %>% filter(substr(term, 1, 1) == "x") %>% pull(estimate)

a1 <- rep(a1, length(a4))
a2 <- rep(a2, length(a4))
a3 <- rep(a3, length(a4))

cffts <- as_tibble(cbind(a1, a2, a3, a4, a5, a6))


cffts <- cffts %>%
  add_column(Year = years[years != a])

ggplot(cffts, aes(x = Year)) +
  geom_line(aes(y = a1 + a6, colour = 'religion')) +
  geom_line(aes(y = a1 + a2 + a4 + a6, colour = 'politics')) +
  geom_line(aes(y = a1 + a3 + a5 + a6, colour = 'science')) +
  scale_color_manual(name = "Legend", values = c('religion' = 'blue', 'politics' = 'red', 'science' = 'green'))+
  labs(title = "20-year bins", x = "Year", y = "Value")

ggsave("../output/results_full_binned.png")

ggplot(subset(cffts, Year %in% seq(1700,1890,1)), aes(x = Year)) +
  geom_line(aes(y = a1 + a6, colour = 'religion')) +
  geom_line(aes(y = a1 + a2 + a4 + a6, colour = 'politics')) +
  geom_line(aes(y = a1 + a3 + a5 + a6, colour = 'science')) +
  scale_color_manual(name = "Legend", values = c('religion' = 'blue', 'politics' = 'red', 'science' = 'green'))+
  labs(title = "20-year bins", x = "Year", y = "Value")

ggsave("../output/results_1700_binned.png")
```

```{r Regression with no bins}

mod <- lm(Percentile ~ Politics + Science + Politics*factor(Year_rounded) + Science*factor(Year_rounded) + factor(Year_rounded), data = df)
summary(mod)
```

```{r Get coefficients}

res <- tidy(mod)

b1 <- res %>% filter(term == "(Intercept)") %>% pull(estimate)
b2 <- res %>% filter(term == "Politics") %>% pull(estimate)
b3 <- res %>% filter(term == "Science") %>% pull(estimate)
b4 <- res %>% filter(substr(term, 1, 9) == "Politics:") %>% pull(estimate)
b5 <- res %>% filter(substr(term, 1, 8) == "Science:") %>% pull(estimate)
b6 <- res %>% filter(substr(term, 1, 6) == "factor") %>% pull(estimate)
yr <- res %>% filter(substr(term, 1, 6) == "factor") %>% pull(term)
yr <- substr(yr, nchar(yr)-3, nchar(yr))
yr <- as.numeric(yr)

b1 <- rep(b1, length(b4))
b2 <- rep(b2, length(b4))
b3 <- rep(b3, length(b4))

betas <- as_tibble(cbind(b1, b2, b3, b4, b5, b6, yr))



ggplot(subset(betas, yr %in% seq(1700,1890,1)), aes(x = yr)) +
  geom_line(aes(y = b1 + b6, colour = 'religion')) +
  geom_line(aes(y = b1 + b2 + b4 + b6, colour = 'politics')) +
  geom_line(aes(y = b1 + b3 + b5 + b6, colour = 'science')) +
  scale_color_manual(name = "Legend", values = c('religion' = 'blue', 'politics' = 'red', 'science' = 'green'))+
  labs(title = "Single-year", x = "Year", y = "Values")

ggsave("../output/results_1700_single.png")

ggplot(subset(betas, yr %in% seq(1500,1900,1)), aes(x = yr)) +
  geom_line(aes(y = b1 + b6, colour = 'religion')) +
  geom_line(aes(y = b1 + b2 + b4 + b6, colour = 'politics')) +
  geom_line(aes(y = b1 + b3 + b5 + b6, colour = 'science')) +
  scale_color_manual(name = "Legend", values = c('religion' = 'blue', 'politics' = 'red', 'science' = 'green'))+
  labs(title = "Single-year", x = "Year", y = "Values")

ggsave("../output/results_full_single.png")

ggplot(subset(betas, yr %in% seq(1700,1900,1)), aes(x = yr)) +
  geom_line(aes(y = b6, colour = 'time')) +
  # geom_line(aes(y = b4, colour = 'politics')) +
  # geom_line(aes(y = b5, colour = 'science')) +
  scale_color_manual(name = "Legend", values = c('time' = 'blue', 'politics' = 'red', 'science' = 'green'))+
  labs(title = "Single-year", x = "Year", y = "Values")

```

```{r Test Code}
z <- volumes %>% 
  filter(bin_20 == 1630) %>%
  lm(Percentile ~ Science + Politics + Science*Religion + Science*Politics + Religion*Politics -Religion, data = .)

y <- lm(Percentile ~ Science + Politics + Science*Religion + Science*Politics + Religion*Politics - Religion, data = volumes)

coefs <- coef(y)

covar <- vcov(y)

delt <- deltamethod(~ x1, coefs, covar)

data <- data.frame(Science = .25, Politics = .25, Religion = 0.5)
prediction <- pred(z, .25, .25, 0.5)



```








